version: '3'

services:
    api:
        build:
            context: .
        container_name: api_fast_test
        command: uvicorn app.main:app --host 0.0.0.0 --port 8008
        restart: always
        volumes:
            - ./app:/app
        environment:
            HOST_PORT: '8008'
        ports:
            - "8008:8008"
        healthcheck:
            test: curl --fail -s http://localhost:8008/healthcheck/ || exit 1
            interval: 1m30s
            timeout: 4s
            retries: 3
